[package]
name = "snapshot-tool"
version = "0.2.0"
authors = ["Rivtower Technologies <contact@rivtower.com>"]
license = "Apache-2.0"
edition = "2018"

[dependencies]
dotenv = "0.13.0"
clap = "2"
fs2 = "0.4.3"
cita-logger = "0.1.0"
util = { https://github.com/ChengyuZhu6/cita-common, branch = "main" }
pubsub = { https://github.com/ChengyuZhu6/cita-common, branch = "main" }
libproto = { https://github.com/ChengyuZhu6/cita-common, branch = "main" }
error =  { https://github.com/ChengyuZhu6/cita-common, branch = "main" }

[features]
default = ["secp256k1", "sha3hash", "rabbitmq"]
secp256k1 = ["libproto/secp256k1"]
ed25519 = ["libproto/ed25519"]
sm2 = ["libproto/sm2"]
sha3hash = ["libproto/sha3hash"]
blake2bhash = ["libproto/blake2bhash"]
sm3hash = ["libproto/sm3hash"]
rabbitmq = ["pubsub/rabbitmq"]
zeromq = ["pubsub/zeromq"]
kafka = ["pubsub/kafka"]
